url: https://notizieterraterra.it
domain: notizieterraterra.it
titolo: Notizie Terra Terra

plugins:
    - jekyll-sitemap
    - jekyll-compress-images
sass:
    sass_dir: ./_scss

exclude:
    - dev/
    - _compress_images_cache.yml
    - .prettierignore
    - README.md

imageoptim:
    svgo: false

collections:
    news:
        output: false